const JWT_MAX_AGE_SECONDS = 3600 * 24 * 3;
const JWT_MAX_AGE_MILLISECONDS = JWT_MAX_AGE_SECONDS * 1000;
const HASH_SALT_ROUNDS = 10;

module.exports = {
    JWT_MAX_AGE_SECONDS,
    JWT_MAX_AGE_MILLISECONDS,
    HASH_SALT_ROUNDS
}